## Exercise 1: Convert a list and tuple into arrays

List to array: 
[1 2 3 4 5 6 7 8]
Tuple to array: 
[[8 4 6]
 [1 2 3]]


In [28]:
import numpy as np

#convert list to array
lst=[1,2,3,4,5,6,7,8]
arr1=np.array(lst)
print("List to array: \n", arr1)

#convert tuple to array
tup=([8,4,6],[1,2,3])
arr2=np.array(tup).reshape(2,3)
print("Tuple to array: \n", arr2)

List to array: 
 [1 2 3 4 5 6 7 8]
Tuple to array: 
 [[8 4 6]
 [1 2 3]]


In [32]:
#using asarray
arr3=np.asarray(lst)
print("List to array using asarray: \n", arr3)
arr4=np.asarray(tup)
print("Tuple to array: \n", arr4)

List to array using asarray: 
 [1 2 3 4 5 6 7 8]
Tuple to array: 
 [[8 4 6]
 [1 2 3]]


## Exercise 2:  Convert the values of Centigrade degrees into Fahrenheit degrees

Values in Fahrenheit degrees:
[ 0.   12.   45.21 34.   99.91]
Values in  Centigrade degrees:
[-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


In [36]:
fah_arr=np.array([0,12,45.21,34,99.91])
cen_arr=(((fah_arr-32)*5)/9)
print("Values in  Fahrenheit degrees:/n",fah_arr)
print("Values in  Centigrade degrees:/n",cen_arr)

Values in  Fahrenheit degrees:/n [ 0.   12.   45.21 34.   99.91]
Values in  Centigrade degrees:/n [-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


## Exercise 3: Write a NumPy program to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements. 

Size of the array:  3
Length of one array element in bytes:  8
Total bytes consumed by the elements of the array:  24


In [64]:
arr5=np.array([1,2.5,3])
print(arr5)
print("Size of the array: ",arr5.size)
print("Length of one array element in bytes: ",arr5.itemsize)
print("Total bytes consumed by the elements of the array: ",arr5.nbytes)

[1.  2.5 3. ]
Size of the array:  3
Length of one array element in bytes:  8
Total bytes consumed by the elements of the array:  24


## Exercise 4: Get the unique elements of an array

Original array:
[10 10 20 20 30 30]
Unique elements of the above array:
[10 20 30]
Original array:
[[1 1]
 [2 3]]
Unique elements of the above array:
[1 2 3]


In [69]:
List9=[10,10,20,20,30,30]
arr9=np.array(List9)
uniq_arr1=np.unique(arr9)
print("Original array: \n",arr9)
print("Unique elements of the above array: \n",uniq_arr1)
List10=[1,1,2,3]
arr10=np.array(List10).reshape((2,2))
uniq_arr2=np.unique(arr10)
print("Original array: \n",arr10)
print("Unique elements of the above array: \n",uniq_arr2)

Original array: 
 [10 10 20 20 30 30]
Unique elements of the above array: 
 [10 20 30]
Original array: 
 [[1 1]
 [2 3]]
Unique elements of the above array: 
 [1 2 3]


## Exercise 5: Change the dimension of an array


Original array: [1 2 3 4 5 6 7 8 9]
Change array shape to (3, 3) -> 3 rows and 3 columns 
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [73]:
list11=[1,2,3,4,5,6,7,8,9]
arr11=np.array(list11)
res_arr=arr11.reshape(3,3)
print("Original array: ",arr11)
print("Change array shape to (3, 3) -> 3 rows and 3 columns \n",res_arr)

Original array:  [1 2 3 4 5 6 7 8 9]
Change array shape to (3, 3) -> 3 rows and 3 columns 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


## Exercise 6: Create a 1-D array of 30 evenly spaced elements between 2.5. and 6.5, inclusive

[2.5        2.63793103 2.77586207 2.9137931  3.05172414 3.18965517
 3.32758621 3.46551724 3.60344828 3.74137931 3.87931034 4.01724138
 4.15517241 4.29310345 4.43103448 4.56896552 4.70689655 4.84482759
 4.98275862 5.12068966 5.25862069 5.39655172 5.53448276 5.67241379
 5.81034483 5.94827586 6.0862069  6.22413793 6.36206897 6.5       ]


In [79]:
arr_1d=np.linspace(2.5,6.5,30)
print(arr_1d)

[2.5        2.63793103 2.77586207 2.9137931  3.05172414 3.18965517
 3.32758621 3.46551724 3.60344828 3.74137931 3.87931034 4.01724138
 4.15517241 4.29310345 4.43103448 4.56896552 4.70689655 4.84482759
 4.98275862 5.12068966 5.25862069 5.39655172 5.53448276 5.67241379
 5.81034483 5.94827586 6.0862069  6.22413793 6.36206897 6.5       ]


## Exercise 7: Convert 1-D arrays as columns into a 2-D array

Array1: [10 20 30]
Array2: [40 50 60]
Converted array
[[10 40]
 [20 50]
 [30 60]]


In [86]:
Array1=np.array([10,20,30])
Array2=np.array([40,50,60])
conv_arr=np.stack((Array1,Array2),axis=1)
print("Array1: ",Array1)
print("Array2: ",Array2)
print("Converted array: \n",conv_arr)

Array1:  [10 20 30]
Array2:  [40 50 60]
Converted array: 
 [[10 40]
 [20 50]
 [30 60]]


## Exercise 8: Create a 5x5 matrix with row values ranging from 0 to 4

Original array:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Row values ranging from 0 to 4.
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [100]:
orig_arr=np.zeros((5,5)) 
print("Original array: \n",orig_arr)
orig_arr[:,1:2]=1
orig_arr[:,2:3]=2
orig_arr[:,3:4]=3
orig_arr[:,4:]=4
print("Row values ranging from 0 to 4. \n",orig_arr)

Original array: 
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Row values ranging from 0 to 4. 
 [[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [112]:
orr = np.zeros((5,5))
print("Original array:")
print(orr)
print("Row values ranging from 0 to 4.")
orr = orr + np.arange(5)
print(orr)

Original array:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Row values ranging from 0 to 4.
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


## Exercise 9: Sum of all the multiples of 3 or 5 below 100

[ 3  5  6  9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50 51
 54 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]
2318


In [128]:
arry=np.arange(1,100)
mul_arr=arry[(arry % 3 == 0) | (arry % 5 ==0)]
sum_val=mul_arr.sum()
print(mul_arr)
print(sum_val)

[ 3  5  6  9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50 51
 54 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]
2318


## Exercise 10: Combine a one and a two dimensional array together and display their elements
##### Hint : np.nditer()

In [28]:
x = np.arange(4)
y = np.arange(4)
for a, b in np.nditer([x,y]):
    print(a)
    print(b)

0
0
1
1
2
2
3
3


One dimensional array:
[0 1 2 3]
Two dimensional array:
[[0 1 2 3]
 [4 5 6 7]]
0:0
1:1
2:2
3:3
0:4
1:5
2:6
3:7


In [139]:
one_d=np.arange(0,4)
two_d=np.arange(0,8).reshape((2,4))
print("One dimensional array: \n",one_d)
print("Two dimensional array: \n",two_d)
for i,j in np.nditer([one_d,two_d]):
    print("{}:{}".format(i,j))

One dimensional array: 
 [0 1 2 3]
Two dimensional array: 
 [[0 1 2 3]
 [4 5 6 7]]
0:0
1:1
2:2
3:3
0:4
1:5
2:6
3:7


## Exercise 11: Write a NumPy program to replace all elements of NumPy array that are greater than specified array.

Original array:
[[0.42436315 0.48558583 0.32924763]
 [0.7439979  0.58220701 0.38213418]
 [0.5097581  0.34528799 0.1563123 ]]
Replace all elements of the said array with .5 which are greater than .5
[[0.42436315 0.48558583 0.32924763]
 [0.5        0.5        0.38213418]
 [0.5        0.34528799 0.1563123 ]]


In [146]:
orr_arry=np.array([[0.42436315,0.48558583,0.32924763],[0.7439979,0.58220701,0.38213418],[0.5097581,0.34528799,0.1563123]])
print("Original array: \n",orr_arry)
orr_arry[orr_arry > 0.5] = 0.5
print("Replace all elements of the said array with .5 which are greater than .5: \n",orr_arry)

Original array: 
 [[0.42436315 0.48558583 0.32924763]
 [0.7439979  0.58220701 0.38213418]
 [0.5097581  0.34528799 0.1563123 ]]
Replace all elements of the said array with .5 which are greater than .5: 
 [[0.42436315 0.48558583 0.32924763]
 [0.5        0.5        0.38213418]
 [0.5        0.34528799 0.1563123 ]]


## Exercise 12: Add a new row to an empty numpy array

Empty array:
[]
After adding two new arrays:
[[10 20 30]
 [40 50 60]]


In [56]:
import numpy as np
emp_arr=np.empty((0,3),int)
print("Empty array: \n",emp_arr)
emp_arr=np.append(emp_arr,([[10,20,30]]),axis=0)
emp_arr=np.append(emp_arr,([[40,50,60]]),axis=0)
print("After adding two new arrays: \n",emp_arr)

Empty array: 
 []
After adding two new arrays: 
 [[10 20 30]
 [40 50 60]]


In [62]:
e_arr=np.array([],int)
print("Empty array: \n",e_arr)
a_arr1=np.array([10,20,30])
a_arr2=np.array([40,50,60])
n_arr=np.stack((a_arr1,a_arr2),axis=0)
print("After adding two new arrays: \n",n_arr)

Empty array: 
 []
After adding two new arrays: 
 [[10 20 30]
 [40 50 60]]


## Exercise 13: Write a NumPy program to join a sequence of arrays along a new axis. 

Original arrays:
[1 2 3]
[2 3 4]
Sequence of arrays along a new axis:
[[1 2 3]
 [2 3 4]]

Original arrays:
[[1]
 [2]
 [3]]

[[2]
 [3]
 [4]]
Sequence of arrays along a new axis:
[[1]
 [2]
 [3]
 [2]
 [3]
 [4]]


In [76]:
orig_arr1=np.arange(1,4)
orig_arr2=np.arange(2,5)
seq_arr1=np.vstack((orig_arr1,orig_arr2))
print("Original arrays: ")
print(orig_arr1)
print(orig_arr2)
print("Sequence of arrays along a new axis: \n",seq_arr1)
orig_arr3=np.array([[1],[2],[3]])
orig_arr4=np.array([[2],[3],[4]])
seq_arr2=np.vstack((orig_arr3,orig_arr4))
print("Original arrays: ")
print(orig_arr3)
print()
print(orig_arr4)
print("Sequence of arrays along a new axis: \n",seq_arr2)

Original arrays: 
[1 2 3]
[2 3 4]
Sequence of arrays along a new axis: 
 [[1 2 3]
 [2 3 4]]
Original arrays: 
[[1]
 [2]
 [3]]

[[2]
 [3]
 [4]]
Sequence of arrays along a new axis: 
 [[1]
 [2]
 [3]
 [2]
 [3]
 [4]]
